version: '3.8'

services:
  # 서비스 이름
  postgres-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    # DB 접속 초기 설정
    environment:
      POSTGRES_USER: quest_admin
      POSTGRES_PASSWORD: quest_password
      POSTGRES_DB: kube_quest_db 
    # 컨테이너가 꺼져도 데이터가 날아가지 않도록 로컬 디스크와 마운트
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    ports:
      - '6379:6379' # redis 기본 포트

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - '4000:3000'
    depends_on:
      - prometheus

# 볼륨 선언
volumes:
  postgres-data: